// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketSimulationsRest.Storage;

#nullable disable

namespace StockMarketSimulationsRest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230507112013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMarketSimulationsRest.Storage.Models.MoneyFlow", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<bool>("IsWithdraw")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TransactionValue")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersWallets");
                });

            modelBuilder.Entity("StockMarketSimulationsRest.Storage.Models.StockTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<bool>("IsBuy")
                        .HasColumnType("bit");

                    b.Property<decimal>("StockCount")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockPriceAtMoment")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TransactionValue")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
